'use client'
import { FormEvent, useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'
import { AuthGuard } from '@/components/auth-guard'
import { supabase } from '@/lib/supabase'
import { Search, X } from 'lucide-react'

type Order={id:string;customer_name:string;phone:string;city:string;product_name:string;quantity:number;price:number;shipping_fee:number;total_amount:number;status:string}
const statuses=[['new','جديد'],['pending_call','في انتظار الاتصال'],['no_answer','لم يجب'],['callback','إعادة الاتصال'],['confirmed','مؤكد'],['ready_to_ship','جاهز للشحن'],['shipped','تم الشحن'],['delivered','تم التسليم'],['cancelled','ملغى'],['returned','مرتجع']]
export default function Orders(){const [orders,setOrders]=useState<Order[]>([]);const [open,setOpen]=useState(false);const [q,setQ]=useState('');async function load(){const {data}=await supabase.from('orders').select('*').order('created_at',{ascending:false});setOrders((data||[]) as Order[])}useEffect(()=>{load()},[]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const payload={customer_name:f.get('customer_name'),phone:f.get('phone'),city:f.get('city'),address:f.get('address'),product_name:f.get('product_name'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),shipping_fee:Number(f.get('shipping_fee')),status:f.get('status')};const {error}=await supabase.from('orders').insert(payload);if(error)alert(error.message);else{setOpen(false);await load()}}
const filtered=orders.filter(o=>(o.customer_name+' '+o.phone).toLowerCase().includes(q.toLowerCase()));return <AuthGuard><AppShell><header className="flex justify-between items-start mb-7"><div><p className="text-violet-600 font-bold">إدارة العمليات</p><h1 className="text-3xl font-extrabold">الطلبيات</h1></div><button onClick={()=>setOpen(true)} className="brand-gradient text-white px-5 py-3 rounded-2xl font-bold">+ إضافة طلب</button></header><div className="card p-4 mb-5 flex gap-3"><div className="relative flex-1"><Search className="absolute right-4 top-3.5 text-slate-400" size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالاسم أو الهاتف" className="w-full border border-slate-200 rounded-2xl pr-12 pl-4 py-3"/></div></div><section className="card overflow-auto"><table className="w-full min-w-[900px]"><thead className="bg-slate-50 text-slate-500"><tr>{['العميل','الهاتف','المدينة','المنتج','الكمية','المبلغ','الحالة'].map(x=><th key={x} className="text-right p-4">{x}</th>)}</tr></thead><tbody>{filtered.map(o=><tr key={o.id} className="border-t border-slate-100"><td className="p-4 font-bold">{o.customer_name}</td><td className="p-4">{o.phone}</td><td className="p-4">{o.city}</td><td className="p-4">{o.product_name}</td><td className="p-4">{o.quantity}</td><td className="p-4">{Number(o.total_amount).toFixed(2)} د.م</td><td className="p-4"><select value={o.status} onChange={async e=>{await supabase.from('orders').update({status:e.target.value}).eq('id',o.id);load()}} className="bg-violet-50 rounded-xl px-3 py-2">{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td></tr>)}</tbody></table></section>{open&&<div className="fixed inset-0 bg-slate-950/50 backdrop-blur-sm grid place-items-center p-4 z-50"><form onSubmit={add} className="card p-6 w-full max-w-2xl max-h-[90vh] overflow-auto"><div className="flex justify-between mb-5"><h2 className="text-2xl font-extrabold">طلب جديد</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="grid md:grid-cols-2 gap-4">{[['customer_name','اسم العميل'],['phone','الهاتف'],['city','المدينة'],['address','العنوان'],['product_name','المنتج'],['quantity','الكمية'],['price','السعر'],['shipping_fee','التوصيل']].map(([n,l])=><label key={n} className="grid gap-2 font-bold">{l}<input name={n} type={['quantity','price','shipping_fee'].includes(n)?'number':'text'} defaultValue={n==='quantity'?'1':n==='shipping_fee'?'0':''} required={!['address'].includes(n)} className="border border-slate-200 rounded-2xl px-4 py-3"/></label>)}<label className="grid gap-2 font-bold md:col-span-2">الحالة<select name="status" className="border border-slate-200 rounded-2xl px-4 py-3">{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><button className="brand-gradient text-white w-full py-3.5 rounded-2xl font-extrabold mt-6">حفظ الطلب</button></form></div>}</AppShell></AuthGuard>}
