'use client'
import { useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'
import { AuthGuard } from '@/components/auth-guard'
import { supabase } from '@/lib/supabase'
import { Box, CheckCircle2, PhoneCall, Truck } from 'lucide-react'

type Order={id:string;customer_name:string;phone:string;city:string;total_amount:number;status:string;created_at:string}
const labels:Record<string,string>={new:'جديد',callback:'إعادة الاتصال',confirmed:'مؤكد',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغى'}
export default function Dashboard(){const [orders,setOrders]=useState<Order[]>([]);useEffect(()=>{supabase.from('orders').select('*').order('created_at',{ascending:false}).then(({data})=>setOrders((data||[]) as Order[]))},[]);const stats=[['إجمالي الطلبات',orders.length,Box],['المؤكدة',orders.filter(x=>x.status==='confirmed').length,CheckCircle2],['إعادة الاتصال',orders.filter(x=>x.status==='callback').length,PhoneCall],['تم التسليم',orders.filter(x=>x.status==='delivered').length,Truck]]
return <AuthGuard><AppShell><header className="flex justify-between items-start mb-7"><div><p className="text-violet-600 font-bold">نظرة عامة</p><h1 className="text-3xl font-extrabold mt-1">لوحة التحكم</h1><p className="text-slate-500 mt-1">متابعة مباشرة لأداء الطلبات والفريق</p></div><a href="/orders" className="brand-gradient text-white px-5 py-3 rounded-2xl font-bold">+ طلب جديد</a></header><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{stats.map(([l,v,I],i)=>{const Icon=I as typeof Box;return <div key={String(l)} className="card p-5"><div className="flex justify-between"><div><p className="text-slate-500">{String(l)}</p><b className="text-3xl block mt-2">{String(v)}</b></div><div className={`w-12 h-12 rounded-2xl grid place-items-center ${i%2?'bg-cyan-50 text-cyan-600':'bg-violet-50 text-violet-600'}`}><Icon/></div></div></div>})}</div><section className="card mt-6 overflow-hidden"><div className="p-5 flex justify-between"><h2 className="font-extrabold text-xl">أحدث الطلبات</h2><a href="/orders" className="text-violet-600 font-bold">عرض الكل</a></div><div className="overflow-auto"><table className="w-full min-w-[720px]"><thead className="bg-slate-50 text-slate-500"><tr>{['العميل','الهاتف','المدينة','المبلغ','الحالة'].map(x=><th key={x} className="text-right p-4">{x}</th>)}</tr></thead><tbody>{orders.slice(0,7).map(o=><tr key={o.id} className="border-t border-slate-100"><td className="p-4 font-bold">{o.customer_name}</td><td className="p-4">{o.phone}</td><td className="p-4">{o.city}</td><td className="p-4">{Number(o.total_amount).toFixed(2)} د.م</td><td className="p-4"><span className="bg-violet-50 text-violet-700 rounded-full px-3 py-1 text-sm font-bold">{labels[o.status]||o.status}</span></td></tr>)}</tbody></table></div></section></AppShell></AuthGuard>}
